#ifndef INCLUDEPATH_H
#define INCLUDEPATH_H

// #define back_normal "C:/Users/New/Huy/asset/images/back-normal.png"
// #define back_hovered "C:/Users/New/Huy/asset/images/back-selected.png"
// #define home_normal "C:/Users/New/Huy/asset/images/home-normal.png"
// #define home_hovered "C:/Users/New/Huy/asset/images/home-selected.png"
// #define menu_avltree_normal "C:/Users/New/Huy/asset/images/menu-avl-normal.png"
// #define menu_avltree_hovered "C:/Users/New/Huy/asset/images/menu-avl-selected.png"
// #define menu_sll_normal "C:/Users/New/Huy/asset/images/menu-maxheap-normal.png"
// #define menu_sll_hovered "C:/Users/New/Huy/asset/images/menu-maxheap-selected.png"
// #define menu_graph_normal "C:/Users/New/Huy/asset/images/menu-graph-normal.png"
// #define menu_graph_hovered "C:/Users/New/Huy/asset/images/menu-graph-selected.png"
// #define menu_hash_normal "C:/Users/New/Huy/asset/images/menu-hash-normal.png"
// #define menu_hash_hoverd "C:/Users/New/Huy/asset/images/menu-hash-selected.png"

// #define font_link_ver2 "C:/Users/New/Huy/asset/Font/Roboto-Regular.ttf"
// #define font_link "C:/Users/New/Huy/asset/Font/PublicSans-Regular.ttf"
// #define PlayButton "C:/Users/New/Huy/asset/images/play-normal.png"
// #define PlayButtonHovered "C:/Users/New/Huy/asset/images/play-selected.png"
// #define PauseButton "C:/Users/New/Huy/asset/images/pause-normal.png"
// #define PauseButtonHovered "C:/Users/New/Huy/asset/images/pause-selected.png"
// #define Replay "C:/Users/New/Huy/asset/images/replay-normal.png"
// #define Replayhovered "C:/Users/New/Huy/asset/images/replay-selected.png"

//QuocHuy
#define back_normal "CS163-DSAVisualization/asset/images/back-normal.png"
#define back_hovered "CS163-DSAVisualization/asset/images/back-selected.png"
#define home_normal "CS163-DSAVisualization/asset/images/home-normal.png"
#define home_hovered "CS163-DSAVisualization/asset/images/home-selected.png"
#define menu_avltree_normal "CS163-DSAVisualization/asset/images/menu-avl-normal.png"
#define menu_avltree_hovered "CS163-DSAVisualization/asset/images/menu-avl-selected.png"
#define menu_sll_normal "CS163-DSAVisualization/asset/images/menu-maxheap-normal.png"
#define menu_sll_hovered "CS163-DSAVisualization/asset/images/menu-maxheap-selected.png"
#define menu_graph_normal "CS163-DSAVisualization/asset/images/menu-graph-normal.png"
#define menu_graph_hovered "CS163-DSAVisualization/asset/images/menu-graph-selected.png"
#define menu_hash_normal "CS163-DSAVisualization/asset/images/menu-hash-normal.png"
#define menu_hash_hoverd "CS163-DSAVisualization/asset/images/menu-hash-selected.png"

#define font_link_ver2 "CS163-DSAVisualization/asset/Font/Roboto-Regular.ttf"
#define font_link "CS163-DSAVisualization/asset/Font/PublicSans-Regular.ttf"
#define PlayButton "CS163-DSAVisualization/asset/images/play-normal.png"
#define PlayButtonHovered "CS163-DSAVisualization/asset/images/play-selected.png"
#define PauseButton "CS163-DSAVisualization/asset/images/pause-normal.png"
#define PauseButtonHovered "CS163-DSAVisualization/asset/images/pause-selected.png"
#define Replay "CS163-DSAVisualization/asset/images/replay-normal.png"
#define Replayhovered "CS163-DSAVisualization/asset/images/replay-selected.png"
#define Skip "CS163-DSAVisualization/asset/Icon/Chevrons right.png"

#endif