#ifndef INCLUDEPATH_H
#define INCLUDEPATH_H

// For Thinh
#define back_normal "D:/Huy/asset/images/back-normal.png"
#define back_hovered "D:/Huy/asset/images/back-selected.png"
#define home_normal "D:/Huy/asset/images/home-normal.png"
#define home_hovered "D:/Huy/asset/images/home-selected.png"
#define menu_avltree_normal "D:/Huy/asset/images/menu-avl-normal.png"
#define menu_avltree_hovered "D:/Huy/asset/images/menu-avl-selected.png"
#define menu_sll_normal "D:/Huy/asset/images/menu-maxheap-normal.png"
#define menu_sll_hovered "D:/Huy/asset/images/menu-maxheap-selected.png"
#define menu_graph_normal "D:/Huy/asset/images/menu-graph-normal.png"
#define menu_graph_hovered "D:/Huy/asset/images/menu-graph-selected.png"
#define menu_hash_normal "D:/Huy/asset/images/menu-hash-normal.png"
#define menu_hash_hoverd "D:/Huy/asset/images/menu-hash-selected.png"

#define font_link_ver2 "D:/Huy/asset/Font/Roboto-Regular.ttf"
#define font_link "D:/Huy/asset/Font/PublicSans-Regular.ttf"
//#define font_link "D:/Huy/asset/Font/SF-Pro-Display-Regular.otf"
#define PlayButton "D:/Huy/asset/images/play-normal.png"
#define PlayButtonHovered "D:/Huy/asset/images/play-selected.png"
#define PauseButton "D:/Huy/asset/images/pause-normal.png"
#define PauseButtonHovered "D:/Huy/asset/images/pause-selected.png"
#define Replay "D:/Huy/asset/images/replay-normal.png"
#define Replayhovered "D:/Huy/asset/images/replay-selected.png"
#define SkipNormal "D:/Huy/asset/images/skip_normal.png"
#define SkipHovered "D:/Huy/asset/images/skip_hovered.png"
#define SkipBackNormal "D:/Huy/asset/images/skipback.png"
#define SkipBackHovered "D:/Huy/asset/images/skipback-hoverd.png"
#define DoubleArrowRight "D:/Huy/asset/images/double-arrow-right-normal.png"
#define DoubleArrowRight_Hovered "D:/Huy/asset/images/double-arrow-right-hovered.png"
#define DoubleArrowLeft "D:/Huy/asset/images/double-arrow-left.png"
#define DoubleArrowLeft_Hovered "D:/Huy/asset/images/double-arrow-left-hoverd.png"
#define sun_light "D:/Huy/asset/Icon/Light.png"
#define sun_dark "D:/Huy/asset/Icon/Dark.png"
#define Rand "D:/Huy/asset/images/Rand.png"

#define TitleMenu "D:/Huy/asset/images/TitleMenu.png"
#define match_cursor_icon "D:/Huy/asset/Icon/pepicons-pencil--pen.png"
#define match_filled_icon "D:/Huy/asset/Icon/pepicons-pencil--pen-circle-filled.png"
#define match_icon "D:/Huy/asset/Icon/pepicons-pencil--pen-circle.png"
#define fill_icon "D:/Huy/asset/Icon/paint-pallet-circle.png"
#define fill_cursor_icon "D:/Huy/asset/Icon/paint-pallet.png"
#define fill_filled_icon "D:/Huy/asset/Icon/paint-pallet-circle-filled.png"
#define scissor_icon "D:/Huy/asset/Icon/scissors-circle.png"
#define scissor_cursor_icon "D:/Huy/asset/Icon/scissors.png"
#define scissor_filled_icon "D:/Huy/asset/Icon/scissors-circle-filled.png"

#endif