#ifndef INCLUDEPATH_H
#define INCLUDEPATH_H

// For QuocHuy
//#define back_normal "CS163-DSAVisualization/asset/images/back-normal.png"
//#define back_hovered "CS163-DSAVisualization/asset/images/back-selected.png"
//#define home_normal "CS163-DSAVisualization/asset/images/home-normal.png"
//#define home_hovered "CS163-DSAVisualization/asset/images/home-selected.png"
//#define menu_avltree_normal "CS163-DSAVisualization/asset/images/menu-avl-normal.png"
//#define menu_avltree_hovered "CS163-DSAVisualization/asset/images/menu-avl-selected.png"
//#define menu_sll_normal "CS163-DSAVisualization/asset/images/menu-maxheap-normal.png"
//#define menu_sll_hovered "CS163-DSAVisualization/asset/images/menu-maxheap-selected.png"
//#define menu_graph_normal "CS163-DSAVisualization/asset/images/menu-graph-normal.png"
//#define menu_graph_hovered "CS163-DSAVisualization/asset/images/menu-graph-selected.png"
//#define menu_hash_normal "CS163-DSAVisualization/asset/images/menu-hash-normal.png"
//#define menu_hash_hoverd "CS163-DSAVisualization/asset/images/menu-hash-selected.png"
//
//#define font_link_ver2 "CS163-DSAVisualization/asset/Font/Roboto-Regular.ttf"
//#define font_link "CS163-DSAVisualization/asset/Font/PublicSans-Regular.ttf"
//#define PlayButton "CS163-DSAVisualization/asset/images/play-normal.png"
//#define PlayButtonHovered "CS163-DSAVisualization/asset/images/play-selected.png"
//#define PauseButton "CS163-DSAVisualization/asset/images/pause-normal.png"
//#define PauseButtonHovered "CS163-DSAVisualization/asset/images/pause-selected.png"
//#define Replay "CS163-DSAVisualization/asset/images/replay-normal.png"
//#define Replayhovered "CS163-DSAVisualization/asset/images/replay-selected.png"
//#define SkipNormal "CS163-DSAVisualization/asset/images/skip_normal.png"
//#define SkipHovered "CS163-DSAVisualization/asset/images/skip_hovered.png"
//#define sun_light "CS163-DSAVisualization/asset/Icon/Light.png"
//#define sun_dark "CS163-DSAVisualization/asset/Icon/Dark.png"
//
//#define TitleMenu "CS163-DSAVisualization/asset/images/TitleMenu.png"

// For Thinh
#define back_normal "CS163-DSAVisualization/asset/images/back-normal.png"
#define back_hovered "CS163-DSAVisualization/asset/images/back-selected.png"
#define home_normal "CS163-DSAVisualization/asset/images/home-normal.png"
#define home_hovered "CS163-DSAVisualization/asset/images/home-selected.png"
#define menu_avltree_normal "CS163-DSAVisualization/asset/images/menu-avl-normal.png"
#define menu_avltree_hovered "CS163-DSAVisualization/asset/images/menu-avl-selected.png"
#define menu_sll_normal "CS163-DSAVisualization/asset/images/menu-maxheap-normal.png"
#define menu_sll_hovered "CS163-DSAVisualization/asset/images/menu-maxheap-selected.png"
#define menu_graph_normal "CS163-DSAVisualization/asset/images/menu-graph-normal.png"
#define menu_graph_hovered "CS163-DSAVisualization/asset/images/menu-graph-selected.png"
#define menu_hash_normal "CS163-DSAVisualization/asset/images/menu-hash-normal.png"
#define menu_hash_hoverd "CS163-DSAVisualization/asset/images/menu-hash-selected.png"

#define font_link_ver2 "CS163-DSAVisualization/asset/Font/Roboto-Regular.ttf"
#define font_link "CS163-DSAVisualization/asset/Font/PublicSans-Regular.ttf"
#define PlayButton "CS163-DSAVisualization/asset/images/play-normal.png"
#define PlayButtonHovered "CS163-DSAVisualization/asset/images/play-selected.png"
#define PauseButton "CS163-DSAVisualization/asset/images/pause-normal.png"
#define PauseButtonHovered "CS163-DSAVisualization/asset/images/pause-selected.png"
#define Replay "CS163-DSAVisualization/asset/images/replay-normal.png"
#define Replayhovered "CS163-DSAVisualization/asset/images/replay-selected.png"
#define SkipNormal "CS163-DSAVisualization/asset/images/skip_normal.png"
#define SkipHovered "CS163-DSAVisualization/asset/images/skip_hovered.png"
#define SkipBackNormal "CS163-DSAVisualization/asset/images/skipback.png"
#define SkipBackHovered "CS163-DSAVisualization/asset/images/skipback-hoverd.png"
#define DoubleArrowRight "CS163-DSAVisualization/asset/images/double-arrow-right-normal.png"
#define DoubleArrowRight_Hovered "CS163-DSAVisualization/asset/images/double-arrow-right-hovered.png"
#define DoubleArrowLeft "CS163-DSAVisualization/asset/images/double-arrow-left.png"
#define DoubleArrowLeft_Hovered "CS163-DSAVisualization/asset/images/double-arrow-left-hoverd.png"
#define sun_light "CS163-DSAVisualization/asset/Icon/Light.png"
#define sun_dark "CS163-DSAVisualization/asset/Icon/Dark.png"
#define Rand "CS163-DSAVisualization/asset/images/Rand.png"

#define TitleMenu "CS163-DSAVisualization/asset/images/TitleMenu.png"
#define match_cursor_icon "CS163-DSAVisualization/asset/Icon/pepicons-pencil--pen.png"
#define match_filled_icon "CS163-DSAVisualization/asset/Icon/pepicons-pencil--pen-circle-filled.png"
#define match_icon "CS163-DSAVisualization/asset/Icon/pepicons-pencil--pen-circle.png"
#define fill_icon "CS163-DSAVisualization/asset/Icon/paint-pallet-circle.png"
#define fill_cursor_icon "CS163-DSAVisualization/asset/Icon/paint-pallet.png"
#define fill_filled_icon "CS163-DSAVisualization/asset/Icon/paint-pallet-circle-filled.png"
#define scissor_icon "CS163-DSAVisualization/asset/Icon/scissors-circle.png"
#define scissor_cursor_icon "CS163-DSAVisualization/asset/Icon/scissors.png"
#define scissor_filled_icon "CS163-DSAVisualization/asset/Icon/scissors-circle-filled.png"
#endif